### ISSUE TITLE
Merge EventQuerySettings into EventQueryChats 

### ISSUE THREAD

**Issue by 0x17de** [HarpoonOrg/Harpoon#1]
used inside src/service/irc/IrcService.cpp.
remove EventQuerySettings and when handing EventQueryChats.
provide all data via EventIrcChatListing. fix all instances where the old event was used

**Comment by hryniuk** [comment]
I see that there are probably an error with initialization.
`EventQueryChats` class has three attributes:

``` cpp
size_t userId;
EventQueue* target;
void* data;
```

but you're passing only two of them, initializing the third one with default value (because of the same name it compiles :astonished:):

``` cpp
EventQueryChats::EventQueryChats(size_t userId, void* data)
    : userId{userId}
    , target{target}
    , data{data}
{}
```

I'll change the constructor to take the third argument called target, ok?

**Comment by 0x17de** [comment]
hmm i remember i wanted to remove the target variable completely - guess i just forgot to remove those lines - i'll have a look

**Comment by 0x17de** [comment]
@hryniuk exactly as i thought - that var can be removed completely as it is not required nor wanted anymore
